"""Prompt templates package."""

from app.prompts.outline import OUTLINE_SYSTEM_PROMPT, OUTLINE_USER_TEMPLATE
from app.prompts.explain import EXPLAIN_SYSTEM_PROMPT, EXPLAIN_USER_TEMPLATE
from app.prompts.draft import DRAFT_SYSTEM_PROMPT, DRAFT_USER_TEMPLATE
from app.prompts.seo import SEO_SYSTEM_PROMPT, SEO_USER_TEMPLATE

__all__ = [
    "OUTLINE_SYSTEM_PROMPT",
    "OUTLINE_USER_TEMPLATE",
    "EXPLAIN_SYSTEM_PROMPT",
    "EXPLAIN_USER_TEMPLATE",
    "DRAFT_SYSTEM_PROMPT",
    "DRAFT_USER_TEMPLATE",
    "SEO_SYSTEM_PROMPT",
    "SEO_USER_TEMPLATE",
]
